### PR TITLE
update to Rust 2018 edition

### PR DESCRIPTION
**Pull request by brayniac**
* changes to update to Rust 2018 edition
* adds Brian Martin <brayniac@gmail.com> to authors
* adding travis-ci

### CODE REVIEW

**Comment by brayniac** [comment]
@photoszzt please review and if you're good with this, we'll merge and I'll ask that you publish to crates.io which will give me the ability to publish updates in the future as well. Thanks!

**Review by photoszzt — APPROVED** [review]
LGTM.

**Comment by photoszzt** [comment]
@brayniac I have published the changes to crates.io.

**Comment by brayniac** [comment]
@photoszzt - thanks! I actually spaced out and forgot that you would need to do a `cargo owner --add` to give me publish rights. Might be possible to do this with `cargo owner --add github:rust-bpf:owners` so the three of us have access to publish (but not to modify owners)? https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

**Comment by photoszzt** [comment]
@brayniac Took me some time to figure out how to do this in github but it's done.

**Pull request merged**
