### PR TITLE
add support for bcc 0.16.0

### PR DESCRIPTION
**Pull request by brayniac**
Adds bindings for bcc 0.16.0 and makes it the new default version

### CODE REVIEW

**Review by javierhonduco — APPROVED** [review]
LGTM, thanks! 🚢 

BTW, maybe it's me being quite new in Rust, but I could not quickly figure out the steps to add support for a new version. Would it be worth it to documents the steps in the README?

**Comment by brayniac** [comment]
@javierhonduco there actually are steps in the README: https://github.com/rust-bpf/bcc-sys#how-to-generate-new-bindings

Take a look there and see if they can be improved or made more clear.

**Comment by javierhonduco** [comment]
I followed them but I got this:

```
$ cargo build --features generate
   Compiling bcc-sys v0.15.2-alpha.0 (/home/javierhonduco/bcc-sys)
error: failed to run custom build command for `bcc-sys v0.15.2-alpha.0 (/home/javierhonduco/bcc-sys)`

Caused by:
  process didn't exit successfully: `/home/javierhonduco/bcc-sys/target/debug/build/bcc-sys-b0106d911aa7cb5d/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=bcc

--- stderr
wrapper.h:2:10: fatal error: 'bcc/bcc_common.h' file not found
wrapper.h:2:10: fatal error: 'bcc/bcc_common.h' file not found, err: true
thread 'main' panicked at 'Should generate BCC API bindings OK: ()', build.rs:93:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have BCC installed, and tried messing with the `PATH`, but no luck. Are you installing the BCC version you want in your path or some other particular place?

I am sure I am doing something obvious wrong :smile:

**Comment by brayniac** [comment]
> I followed them but I got this:
> 
> ```
> $ cargo build --features generate
>    Compiling bcc-sys v0.15.2-alpha.0 (/home/javierhonduco/bcc-sys)
> error: failed to run custom build command for `bcc-sys v0.15.2-alpha.0 (/home/javierhonduco/bcc-sys)`
> 
> Caused by:
>   process didn't exit successfully: `/home/javierhonduco/bcc-sys/target/debug/build/bcc-sys-b0106d911aa7cb5d/build-script-build` (exit code: 101)
> --- stdout
> cargo:rustc-link-lib=bcc
> 
> --- stderr
> wrapper.h:2:10: fatal error: 'bcc/bcc_common.h' file not found
> wrapper.h:2:10: fatal error: 'bcc/bcc_common.h' file not found, err: true
> thread 'main' panicked at 'Should generate BCC API bindings OK: ()', build.rs:93:19
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> I have BCC installed, and tried messing with the `PATH`, but no luck. Are you installing the BCC version you want in your path or some other particular place?
> 
> I am sure I am doing something obvious wrong

@javierhonduco - can you open an issue for this. Please include details about OS and whether BCC was installed via an OS package or from source. If from source, include the commands used to build. I suspect it's a library path issue.

**Pull request merged**
